version: '2'

networks:
  http:
    external: true

services:
  traefik:
    image: traefik:v1.7-alpine
    command: --api --docker -c /opt/traefik/traefik.toml
    restart: always
    networks:
      - http
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8080:8080"
    environment:
      DO_AUTH_TOKEN: ${DO_AUTH_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/traefik/traefik.toml:/traefik.toml
      - /docker/traefik/acme.json:/acme.json
