version: '2'

networks:
  torrent:
    external: true
  http:
    external: true

services:
  radarr:
    image: linuxserver/radarr
    restart: always
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/London
    networks:
    - default
    - torrent
    volumes:
    - /docker/radarr:/config
    - /ds/movies:/movies
    - /ds/torrent:/ds/torrent
  oauth:
    extends:
      file: ../oauth/docker-compose.yml
      service: oauth
    command:
      - http://radarr:7878
