version: '2.1'

networks:
  torrent:
    external: true
  http:
    external: true

services:
  vpn:
    extends:
      file: ../base/docker-compose.yml
      service: application
    image: dperson/openvpn-client
    tty: true
    security_opt:
      - label:disable
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /dev/net:/dev/net:z
      - /docker/vpn:/vpn
    command: -f 8112 -d
  deluge:
    extends:
      file: ../base/docker-compose.yml
      service: application
    image: linuxserver/deluge:5b398f77-ls22
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/London
      UMASK_SET: '002'
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
    - /docker/deluge:/config
    - /ds/torrent:/ds/torrent
    tty: true
  deluge-api:
    extends:
      file: ../base/docker-compose.yml
      service: application
    image: hpello/tcp-proxy
    depends_on:
      - deluge
    links:
      - vpn:deluge
    networks:
      - default
      - torrent
    command: deluge 8112
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8112"]    
  jackett:
    extends:
      file: ../base/docker-compose.yml
      service: application
    image: linuxserver/jackett
    environment:
      TZ: Europe/London
      PUID: 1000
      PGID: 1000
    depends_on:
      - vpn
    network_mode: "service:vpn"
    volumes:
      - /docker/jackett:/config
    tty: true
  jackett-api:
    extends:
      file: ../base/docker-compose.yml
      service: application
    image: hpello/tcp-proxy
    depends_on:
      - jackett
    links:
      - vpn:jackett
    networks:
      - default
      - torrent
    command: jackett 9117
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9117/UI/Login"]
  deluge-oauth:
    extends:
      file: ../oauth/docker-compose.yml
      service: oauth
    labels:
      traefik.frontend.rule: "Host:${DELUGE_VIRTUAL_HOST}"
    command:
      - http://deluge-api:8112
  jackett-oauth:
    extends:
      file: ../oauth/docker-compose.yml
      service: oauth
    labels:
      traefik.frontend.rule: "Host:${JACKETT_VIRTUAL_HOST}"
    command:
      - http://jackett-api:9117
