version: '2'
networks:
  http:
    external: true
services:
  oauth:
    image: quay.io/pusher/oauth2_proxy
    volumes:
      - /docker/auth:/config/
    restart: on-failure
    networks:
      - default
      - http
    env_file: ./.env
    environment:
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_APPROVAL_PROMPT: auto
    labels:
      traefik.enable: "true"
      traefik.port: "9000"
      traefik.docker.network: "http"
      traefik.frontend.rule: "Host:${VIRTUAL_HOST}"
    entrypoint:
      - /bin/oauth2_proxy
      - --http-address=0.0.0.0:9000
      - --authenticated-emails-file=/config/emails.txt
      - --upstream
